### ISSUE TITLE
ticktock stream deployment error

### ISSUE THREAD

**Issue by linusviking** [spring-cloud/spring-cloud-dataflow-server-kubernetes#102]
I've set up kafka, mysql, and scdf services & rc on a Kubernetes 1.2 cluster - I used NodePorts instead of LoadBalancer in the scdf service and with that I am about to open the dashboard on localhost. I am stuck at step 10 of the example (http://docs.spring.io/spring-cloud-dataflow-server-kubernetes/docs/1.0.0.RELEASE/reference/htmlsingle/). I am able to register docker:springcloudstream/time-source-kafka:latest as source & docker:springcloudstream/log-sink-kafka:latest sink but deployment of "stream create --name ticktock --definition "time | log" --deploy" is failing with the following exceptions: 

`2016-08-31T15:00:59.420555172Z Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
2016-08-31T15:00:59.420567646Z  at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387) ~[na:1.8.0_92-internal]
2016-08-31T15:00:59.420574991Z  at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292) ~[na:1.8.0_92-internal]
2016-08-31T15:00:59.420582081Z  at sun.security.validator.Validator.validate(Validator.java:260) ~[na:1.8.0_92-internal]
2016-08-31T15:00:59.420588738Z  at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324) ~[na:1.8.0_92-internal]
2016-08-31T15:00:59.420595581Z  at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229) ~[na:1.8.0_92-internal]
2016-08-31T15:00:59.420602522Z  at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124) ~[na:1.8.0_92-internal]
2016-08-31T15:00:59.420609339Z  at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1491) ~[na:1.8.0_92-internal]
2016-08-31T15:00:59.420616163Z  ... 98 common frames omitted
2016-08-31T15:00:59.420622474Z Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
`
Could you please suggest what could be going wrong?

**Comment by trisberg** [comment]
Do you have the correct URI for `KUBERNETES_MASTER` in your `scdf-controller.yml`? You can check the current value with `kubectl describe pod scdf`. It should match the value returned by `kubectl cluster-info`, look for `Kubernetes master is running at `.

**Comment by linusviking** [comment]
Yes, the scdf server can connect to the kubernetes master, the mysql test database is also populated when I register the time & log modules. The certification path error comes up when I try to deploy the ticktock stream.

**Comment by trisberg** [comment]
Where do you see this exception? Can you post the complete stacktrace?

**Comment by linusviking** [comment]
In the log of the scdf server replication controller. Here's a link to the complete stacktrace: https://gist.github.com/linusviking/44f2fe38961f3aa88b00c6785cb10b43

**Comment by trisberg** [comment]
I don't recognize the logging pattern - `2016-09-01T10:13:23.166360314Z 2016-09-01 10:13:23.121  INFO` - is this a custom build or the docker image from `springcloud/spring-cloud-dataflow-server-kubernetes`

**Comment by linusviking** [comment]
Yes, I'd built a custom image. I get the same "certification path to requested target not found" with the docker image from springcloud/spring-cloud-dataflow-server-kubernetes. Here's the complete stacktrace: https://gist.github.com/linusviking/a03c274b91e16131423c6750fa911321 

The file not found errors at line 191 & 277 were caused when I tried to create the ticktock stream without registering the apps. Errors from line 358 were caused after post registration of the time & log apps.

**Comment by trisberg** [comment]
Is this on a Google Container Engine cluster or some other cluster. Maybe you are missing the necessary CA certificates for Java to use SSL?

**Comment by linusviking** [comment]
I am deploying on a local K8 cluster. Is there a way to disable SSL on the Spring Cloud Dataflow server?

**Comment by trisberg** [comment]
Clearing out old issues - did you ever get this resolved? If not please re-open this issue and post the entire stack trace so we can se where it is coming from.
