### ISSUE TITLE
Document that SCDF for Kubernetes only supports Docker resources --  Unable to get URI for ServletContext resource [/maven://xxxx]

### ISSUE THREAD

**Issue by geoand** [spring-cloud/spring-cloud-dataflow-server-kubernetes#157]
Hello,

I have currently deployed Spring Cloud Data Flow for Kubernetes (version 1.1.0.RELEASE) inside an on-premise Kubernetes cluster (created with kubeadm).
I am also using RabbitMQ as the messaging middleware and PostgreSQL as the database for Spring Cloud Data Flow.

When I created the standard `ticktock` stream (`time | log`) using the corresponding Docker starter apps, everything worked as expected.
However when I tried to do deploy the same stream (after properly destroying the old stream of course) using the Maven starter apps, I got the following exception in the logs and the stream was not deployed:

```
 2016-12-06T13:39:34.182811000Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
2016-12-06T13:39:34.183122000Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [tomcat-embed-core-8.5.5.jar!/:8.5.5]
2016-12-06T13:39:34.183393000Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [tomcat-embed-core-8.5.5.jar!/:8.5.5]
2016-12-06T13:39:34.183661000Z 	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:105) [spring-boot-actuator-1.4.1.RELEASE.jar!/:1.4.1.RELEASE]
2016-12-06T13:39:34.183959000Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
2016-12-06T13:39:34.184227000Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [tomcat-embed-core-8.5.5.jar!/:8.5.5]
2016-12-06T13:39:34.184502000Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [tomcat-embed-core-8.5.5.jar!/:8.5.5]
2016-12-06T13:39:34.184786000Z 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:208) [spring-security-web-4.1.3.RELEASE.jar!/:4.1.3.RELEASE]
2016-12-06T13:39:34.185076000Z 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177) [spring-security-web-4.1.3.RELEASE.jar!/:4.1.3.RELEASE]
2016-12-06T13:39:34.185702000Z 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346) [spring-web-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
2016-12-06T13:39:34.186006000Z 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262) [spring-web-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
2016-12-06T13:39:34.186274000Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [tomcat-embed-core-8.5.5.jar!/:8.5.5]
2016-12-06T13:39:34.186557000Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [tomcat-embed-core-8.5.5.jar!/:8.5.5]
2016-12-06T13:39:34.186847000Z 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) [spring-web-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
2016-12-06T13:39:34.187139000Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
2016-12-06T13:39:34.187415000Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [tomcat-embed-core-8.5.5.jar!/:8.5.5]
2016-12-06T13:39:34.187692000Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [tomcat-embed-core-8.5.5.jar!/:8.5.5]
2016-12-06T13:39:34.188518000Z 	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:89) [spring-web-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
2016-12-06T13:39:34.188798000Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
2016-12-06T13:39:34.189090000Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [tomcat-embed-core-8.5.5.jar!/:8.5.5]
2016-12-06T13:39:34.189357000Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [tomcat-embed-core-8.5.5.jar!/:8.5.5]
2016-12-06T13:39:34.189620000Z 	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77) [spring-web-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
2016-12-06T13:39:34.189897000Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
2016-12-06T13:39:34.190180000Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [tomcat-embed-core-8.5.5.jar!/:8.5.5]
2016-12-06T13:39:34.190522000Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [tomcat-embed-core-8.5.5.jar!/:8.5.5]
2016-12-06T13:39:34.190800000Z 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197) [spring-web-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
2016-12-06T13:39:34.191078000Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
2016-12-06T13:39:34.191352000Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [tomcat-embed-core-8.5.5.jar!/:8.5.5]
2016-12-06T13:39:34.191630000Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [tomcat-embed-core-8.5.5.jar!/:8.5.5]
2016-12-06T13:39:34.191885000Z 	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:107) [spring-boot-actuator-1.4.1.RELEASE.jar!/:1.4.1.RELEASE]
2016-12-06T13:39:34.192176000Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
2016-12-06T13:39:34.192445000Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [tomcat-embed-core-8.5.5.jar!/:8.5.5]
2016-12-06T13:39:34.192706000Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [tomcat-embed-core-8.5.5.jar!/:8.5.5]
2016-12-06T13:39:34.193057000Z 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) [tomcat-embed-core-8.5.5.jar!/:8.5.5]
2016-12-06T13:39:34.193322000Z 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108) [tomcat-embed-core-8.5.5.jar!/:8.5.5]
2016-12-06T13:39:34.194014000Z 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) [tomcat-embed-core-8.5.5.jar!/:8.5.5]
2016-12-06T13:39:34.194282000Z 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.5.jar!/:8.5.5]
2016-12-06T13:39:34.194537000Z 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [tomcat-embed-core-8.5.5.jar!/:8.5.5]
2016-12-06T13:39:34.194805000Z 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.5.jar!/:8.5.5]
2016-12-06T13:39:34.195088000Z 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349) [tomcat-embed-core-8.5.5.jar!/:8.5.5]
2016-12-06T13:39:34.195349000Z 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:784) [tomcat-embed-core-8.5.5.jar!/:8.5.5]
 2016-12-06T13:39:34.195625000Z 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.5.jar!/:8.5.5]
2016-12-06T13:39:34.195985000Z 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:802) [tomcat-embed-core-8.5.5.jar!/:8.5.5]
2016-12-06T13:39:34.196240000Z 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1410) [tomcat-embed-core-8.5.5.jar!/:8.5.5]
2016-12-06T13:39:34.196492000Z 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.5.jar!/:8.5.5]
2016-12-06T13:39:34.196784000Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_92-internal]
2016-12-06T13:39:34.197430000Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_92-internal]
2016-12-06T13:39:34.197695000Z 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.5.jar!/:8.5.5]
2016-12-06T13:39:34.197965000Z 	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_92-internal]
2016-12-06T13:39:34.198238000Z Caused by: java.io.FileNotFoundException: ServletContext resource [/maven://org.springframework.cloud.stream.app:log-sink-rabbit:1.0.2.RELEASE] cannot be resolved to URL because it does not exist
2016-12-06T13:39:34.198500000Z 	at org.springframework.web.context.support.ServletContextResource.getURL(ServletContextResource.java:156) ~[spring-web-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
2016-12-06T13:39:34.198762000Z 	at org.springframework.core.io.AbstractResource.getURI(AbstractResource.java:99) ~[spring-core-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
2016-12-06T13:39:34.199030000Z 	at org.springframework.cloud.deployer.spi.kubernetes.DefaultContainerFactory.create(DefaultContainerFactory.java:69) ~[spring-cloud-deployer-kubernetes-1.1.0.RELEASE.jar!/:1.1.0.RELEASE]
2016-12-06T13:39:34.199314000Z 	... 77 common frames omitted 
````

Please let me know if you need any further information to investigate.

Thank you very much for your time and for this amazing project!
George

**Comment by spilio** [comment]
Hi,

I got the same error while trying to register and launch a task application through the Shell.

**Comment by geoand** [comment]
Through debugging I have come to the conclusion that Maven deployment is not supported for the Kubernetes runtime. 
This is due to the fact that `DelegatingResourceLoader` bean only delegates to `DockerResourceLoader` (no maven configuration), and even if it did, the implementation of `DefaultContainerFactory` which uses the `getURI` method would not work for maven, because the `MavenResource` does not implement that method.

If my analysis is correct and the Kubernetes specific runtime of Spring Cloud Dataflow does not support Maven, then I think the documents need to updated to indicate this. Also the import procedure should not allow the use of maven definitions.
I am mentioning this because reading the docs and using the UI, I was under the impression that Spring Cloud Dataflow for Kubernetes would implicitly convert the Maven artifact into a Docker image and deploy that to Kubernetes.

Any comments would be most welcome

**Comment by donovanmuller** [comment]
@geoand You are correct. The Kubernetes deployer only supports Docker resources as Kubernetes itself only supports deploying Docker containers.

For interest sake, if you require Maven as well as Docker support in a Kubernetes like environment, then there is an [OpenShift](https://www.openshift.org/) server available: https://github.com/donovanmuller/spring-cloud-dataflow-server-openshift..

**Comment by geoand** [comment]
@donovanmuller Thank you for the clarification!

I think it would be great if this fact where reflected in both the Docs and the UI

Regards

**Comment by trisberg** [comment]
We'll add this in the docs for next version

**Comment by geoand** [comment]
@trisberg Thanks a lot!
