### ISSUE TITLE
Skipping the optional skipper setup ends up with server deployment errors

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-kubernetes#247]
As a user, I'm following the [getting-started](https://docs.spring.io/spring-cloud-dataflow-server-kubernetes/docs/1.3.0.BUILD-SNAPSHOT/reference/htmlsingle/#_deploying_using_kubectl) guide to setup SCDF; however, when I skip the optional step to setup skipper, I get the following deployment error.

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.skipper.client.SkipperClient]: Factory method 'skipperClient' threw exception; nested exception is java.lang.IllegalStateException: Bad URI syntax: http://${SKIPPER_SERVICE_HOST}/api
    at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189) ~[spring-beans-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
    at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588) ~[spring-beans-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
    ... 26 common frames omitted
```

This is happening because `server-deployment.yaml` expects the Skipper URI since it is parameterized. It might be better (/ easy fix) to [update the docs](https://docs.spring.io/spring-cloud-dataflow-server-kubernetes/docs/1.3.0.BUILD-SNAPSHOT/reference/htmlsingle/#_deploying_using_kubectl) [i.e., `6. Deploy Skipper` section] to include Skipper always in the getting-started guide.

**Comment by sabbyanandan** [comment]
This is addressed via: https://github.com/spring-cloud/spring-cloud-dataflow-server-kubernetes/commit/a44eecf144b558f96b4685fca51c05a3e69e2246.
