### ISSUE TITLE
kafka <====> zookepr timeout on kubernetes

### ISSUE THREAD

**Issue by scne** [spring-cloud/spring-cloud-dataflow-server-kubernetes#298]
I've same problem with kubernetes

**kafka-deployment.yml**
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka-broker
  labels:
    app: kafka
    component: kafka-broker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
        component: kafka-broker
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka:0.10.1.0
        ports:
        - containerPort: 9092
        env:
          - name: ENABLE_AUTO_EXTEND
            value: "true"
          - name: KAFKA_RESERVED_BROKER_MAX_ID
            value: "9"
          - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
            value: "false"
          - name: KAFKA_PORT
            value: "9092"
          - name: KAFKA_ADVERTISED_PORT
            value: "9092"
          - name: KAFKA_ADVERTISED_HOST_NAME
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: kafka-zk:2181
          - name: KAFKA_ZOOKEEPER_TIMEOUT_MS
            value: 1600
```

**kafka-zk-deployment.yml**

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka-zk
  labels:
    app: kafka
    component: kafka-zk
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-zk
        component: kafka-zk
    spec:
      containers:
      - name: kafka-zk
        image: digitalwonderland/zookeeper
        ports:
        - containerPort: 2181
        env:
        - name: ZOOKEEPER_ID
          value: "1"
        - name: ZOOKEEPER_SERVER_1
          value: kafka-zk
```

But KAFKA_ZOOKEEPER_TIMEOUT_MS not change

```
...
zookeeper.connect = kafka-zk:2181
	zookeeper.connection.timeout.ms = 6000
	zookeeper.session.timeout.ms = 6000
	zookeeper.set.acl = false
	zookeeper.sync.time.ms = 2000
 (kafka.server.KafkaConfig)
[2018-06-19 13:12:36,415] INFO starting (kafka.server.KafkaServer)
[2018-06-19 13:12:36,429] INFO [ThrottledRequestReaper-Fetch], Starting  (kafka.server.ClientQuotaManager$ThrottledRequestReaper)
[2018-06-19 13:12:36,431] INFO [ThrottledRequestReaper-Produce], Starting  (kafka.server.ClientQuotaManager$ThrottledRequestReaper)
[2018-06-19 13:12:36,434] INFO Connecting to zookeeper on kafka-zk:2181 (kafka.server.KafkaServer)
[2018-06-19 13:12:36,450] INFO Starting ZkClient event thread. (org.I0Itec.zkclient.ZkEventThread)
[2018-06-19 13:12:36,457] INFO Client environment:zookeeper.version=3.4.8--1, built on 02/06/2016 03:18 GMT (org.apache.zookeeper.ZooKeeper)
[2018-06-19 13:12:36,457] INFO Client environment:host.name=kafka-broker-6bc7d7944b-vcvgl (org.apache.zookeeper.ZooKeeper)
[2018-06-19 13:12:36,457] INFO Client environment:java.version=1.8.0_102 (org.apache.zookeeper.ZooKeeper)
.......
[2018-06-19 13:12:36,459] INFO Initiating client connection, connectString=kafka-zk:2181 sessionTimeout=6000 watcher=org.I0Itec.zkclient.ZkClient@6ca8564a (org.apache.zookeeper.ZooKeeper)
waiting for kafka to be ready
[2018-06-19 13:12:46,057] INFO Waiting for keeper state SyncConnected (org.I0Itec.zkclient.ZkClient)
[2018-06-19 13:12:52,058] INFO Terminate ZkClient event thread. (org.I0Itec.zkclient.ZkEventThread)
waiting for kafka to be ready
waiting for kafka to be ready
[2018-06-19 13:13:06,075] INFO Opening socket connection to server kafka-zk.default.svc.cluster.local/10.103.156.248:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-06-19 13:13:06,143] INFO Socket connection established to kafka-zk.default.svc.cluster.local/10.103.156.248:2181, initiating session (org.apache.zookeeper.ClientCnxn)
[2018-06-19 13:13:06,153] INFO Session establishment complete on server kafka-zk.default.svc.cluster.local/10.103.156.248:2181, sessionid = 0x1641825a8dc0006, negotiated timeout = 6000 (org.apache.zookeeper.ClientCnxn)
[2018-06-19 13:13:06,162] INFO Session: 0x1641825a8dc0006 closed (org.apache.zookeeper.ZooKeeper)
[2018-06-19 13:13:06,164] INFO EventThread shut down for session: 0x1641825a8dc0006 (org.apache.zookeeper.ClientCnxn)
[2018-06-19 13:13:06,163] FATAL Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
org.I0Itec.zkclient.exception.ZkTimeoutException: Unable to connect to zookeeper server within timeout: 6000
	at org.I0Itec.zkclient.ZkClient.connect(ZkClient.java:1232)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:156)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:130)
	at kafka.utils.ZkUtils$.createZkClientAndConnection(ZkUtils.scala:76)
	at kafka.utils.ZkUtils$.apply(ZkUtils.scala:58)
	at kafka.server.KafkaServer.initZk(KafkaServer.scala:327)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:200)
	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:39)
	at kafka.Kafka$.main(Kafka.scala:67)
	at kafka.Kafka.main(Kafka.scala)
[2018-06-19 13:13:06,166] INFO shutting down (kafka.server.KafkaServer)
[2018-06-19 13:13:06,170] INFO shut down completed (kafka.server.KafkaServer)
[2018-06-19 13:13:06,171] FATAL Fatal error during KafkaServerStartable startup. Prepare to shutdown (kafka.server.KafkaServerStartable)
org.I0Itec.zkclient.exception.ZkTimeoutException: Unable to connect to zookeeper server within timeout: 6000
	at org.I0Itec.zkclient.ZkClient.connect(ZkClient.java:1232)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:156)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:130)
	at kafka.utils.ZkUtils$.createZkClientAndConnection(ZkUtils.scala:76)
	at kafka.utils.ZkUtils$.apply(ZkUtils.scala:58)
	at kafka.server.KafkaServer.initZk(KafkaServer.scala:327)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:200)
	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:39)
	at kafka.Kafka$.main(Kafka.scala:67)
	at kafka.Kafka.main(Kafka.scala)
[2018-06-19 13:13:06,172] INFO shutting down (kafka.server.KafkaServer)
```

**Comment by chrisjs** [comment]
for reference looks like this was posted to the wurstmeister docker image for kafka as well - https://github.com/wurstmeister/kafka-docker/issues/249

**Comment by chrisjs** [comment]
Looks like `KAFKA_ZOOKEEPER_TIMEOUT_MS` is not the correct env var. In `spring-cloud-dataflow-server-kubernetes/src/kubernetes/kafka/kafka-deployment.yaml` I added:

```
          - name: KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS
            value: "1600"
```

Then when starting the server I can see:

```
zookeeper.connection.timeout.ms = 1600
```

**Comment by chrisjs** [comment]
@brijeshkumar1 seems to be a different issue than the original. in your stack trace i see:

```
[2018-10-27 06:32:55,991] WARN Session 0x0 for server zoo1:2181, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.nio.channels.UnresolvedAddressException
```

looks like `zoo1` isn't resolvable in this case

**Comment by kpmadhan** [comment]
> Hi
> I am also facing same issue.
> environment:java.library.path=/usr/lib/jvm/java-1.8-openjdk/jre/lib/amd64/server:/usr/lib/jvm/java-1.8-openjdk/jre/lib/amd64:/usr/lib/jvm/java-1.8-openjdk/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib (org.apache.zookeeper.ZooKeeper)
> [2018-10-27 06:32:50,947] INFO Client environment:java.io.tmpdir=/tmp (org.apache.zookeeper.ZooKeeper)
> [2018-10-27 06:32:50,947] INFO Client environment:java.compiler= (org.apache.zookeeper.ZooKeeper)
> [2018-10-27 06:32:50,947] INFO Client environment:os.name=Linux (org.apache.zookeeper.ZooKeeper)
> [2018-10-27 06:32:50,947] INFO Client environment:os.arch=amd64 (org.apache.zookeeper.ZooKeeper)
> [2018-10-27 06:32:50,948] INFO Client environment:os.version=3.10.0-862.14.4.el7.x86_64 (org.apache.zookeeper.ZooKeeper)
> [2018-10-27 06:32:50,948] INFO Client environment:user.name=root (org.apache.zookeeper.ZooKeeper)
> [2018-10-27 06:32:50,948] INFO Client environment:user.home=/root (org.apache.zookeeper.ZooKeeper)
> [2018-10-27 06:32:50,948] INFO Client environment:user.dir=/ (org.apache.zookeeper.ZooKeeper)
> [2018-10-27 06:32:50,950] INFO Initiating client connection, connectString=zoo1:2181 sessionTimeout=6000 watcher=kafka.zookeeper.ZooKeeperClient$ZooKeeperClientWatcher$@223d2c72 (org.apache.zookeeper.ZooKeeper)
> [2018-10-27 06:32:50,974] INFO [ZooKeeperClient] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
> [2018-10-27 06:32:55,980] INFO Opening socket connection to server zoo1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
> [2018-10-27 06:32:55,991] WARN Session 0x0 for server zoo1:2181, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
> java.nio.channels.UnresolvedAddressException
> at sun.nio.ch.Net.checkAddress(Net.java:101)
> at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:622)
> at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277)
> at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287)
> at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1021)
> at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1064)
> [2018-10-27 06:32:56,978] INFO [ZooKeeperClient] Closing. (kafka.zookeeper.ZooKeeperClient)
> [2018-10-27 06:32:57,098] INFO Opening socket connection to server zoo1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
> [2018-10-27 06:32:57,203] INFO Session: 0x0 closed (org.apache.zookeeper.ZooKeeper)
> [2018-10-27 06:32:57,203] INFO EventThread shut down for session: 0x0 (org.apache.zookeeper.ClientCnxn)
> [2018-10-27 06:32:57,206] INFO [ZooKeeperClient] Closed. (kafka.zookeeper.ZooKeeperClient)
> [2018-10-27 06:32:57,210] ERROR Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
> kafka.zookeeper.ZooKeeperClientTimeoutException: Timed out waiting for connection while in state: CONNECTING
> at kafka.zookeeper.ZooKeeperClient$$anonfun$kafka$zookeeper$ZooKeeperClient$$waitUntilConnected$1.apply$mcV$sp(ZooKeeperClient.scala:230)
> at kafka.zookeeper.ZooKeeperClient$$anonfun$kafka$zookeeper$ZooKeeperClient$$waitUntilConnected$1.apply(ZooKeeperClient.scala:226)
> at kafka.zookeeper.ZooKeeperClient$$anonfun$kafka$zookeeper$ZooKeeperClient$$waitUntilConnected$1.apply(ZooKeeperClient.scala:226)
> at kafka.utils.CoreUtils$.inLock(CoreUtils.scala:251)
> at kafka.zookeeper.ZooKeeperClient.kafka$zookeeper$ZooKeeperClient$$waitUntilConnected(ZooKeeperClient.scala:226)
> at kafka.zookeeper.ZooKeeperClient.(ZooKeeperClient.scala:95)
> at kafka.zk.KafkaZkClient$.apply(KafkaZkClient.scala:1580)
> at kafka.server.KafkaServer.kafka$server$KafkaServer$$createZkClient$1(KafkaServer.scala:348)
> at kafka.server.KafkaServer.initZkClient(KafkaServer.scala:372)
> at kafka.server.KafkaServer.startup(KafkaServer.scala:202)
> at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
> at kafka.Kafka$.main(Kafka.scala:75)
> at kafka.Kafka.main(Kafka.scala)
> [2018-10-27 06:32:57,212] INFO shutting down (kafka.server.KafkaServer)
> [2018-10-27 06:32:57,214] WARN (kafka.utils.CoreUtils$)
> java.lang.NullPointerException
> at kafka.server.KafkaServer$$anonfun$shutdown$5.apply$mcV$sp(KafkaServer.scala:579)
> at kafka.utils.CoreUtils$.swallow(CoreUtils.scala:86)
> at kafka.server.KafkaServer.shutdown(KafkaServer.scala:579)
> at kafka.server.KafkaServer.startup(KafkaServer.scala:329)
> at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
> at kafka.Kafka$.main(Kafka.scala:75)
> at kafka.Kafka.main(Kafka.scala)
> [2018-10-27 06:32:57,220] INFO shut down completed (kafka.server.KafkaServer)
> [2018-10-27 06:32:57,220] ERROR Exiting Kafka. (kafka.server.KafkaServerStartable)
> [2018-10-27 06:32:57,223] INFO shutting down (kafka.server.KafkaServer)
> [root@madhu-k8-master01 kafka-deployment-test]#

@brijeshkumar1 did you find a solution for the issue ? I am facing the same !!
