### ISSUE TITLE
NullPointerException - Creating a schedule of a task in SCDF Dashboard

### ISSUE THREAD

**Issue by rdegracia** [spring-cloud/spring-cloud-dataflow-server-kubernetes#375]
**Description:**
When creating a Schedule with cron expression of the task by clicking on "Schedule the task" in SCDF dashboard, NullPointerException is thrown. SCDF server with Kafka is deployed in Kubernetes.

**Release versions:**
<artifactId>spring-cloud-scheduler-kubernetes</artifactId>
<version>1.1.0.BUILD-SNAPSHOT</version>

**Stacktrace**
NullPointerException is thrown in below line of KubernetesScheduler class:
(https://github.com/spring-cloud/spring-cloud-scheduler-kubernetes/blob/master/src/main/java/org/springframework/cloud/scheduler/spi/kubernetes/KubernetesScheduler.java)

String invalidCronExceptionMessage = getExceptionMessageForField(e, SCHEDULE_EXPRESSION_FIELD_NAME);

**Comment by chrisjs** [comment]
@rdegracia what are the exact versions of scdf/skipper/etc, steps, and so on to be used in order to reproduce?

**Comment by rdegracia** [comment]
@chrisjs 
spring-cloud-dataflow-server-kubernetes-parent - 2.0.0.BUILD-SNAPSHOT
There is no skipper, no metrics, no roles creation and I used default in-mem db

steps:
A. kubectl command 
538  cd spring-cloud-dataflow-server-kubernetes/
  539  ls
  540  more src/kubernetes/kafka/
  541  more src/kubernetes/kafka/kafka-deployment.yaml
  542  kubectl create -f src/kubernetes/kafka/
  543  kubectl get pods
  544  kubectl get all -l
  545  kubectl get all -l app=kafka
  546 kubectl create -f src/kubernetes/server/server-svc.yaml
  547 kubectl create -f src/kubernetes/server/server-deployment.yaml

B. Access dashboard
1. Create App
2. Create Task
3. From #2, create a schedule with cron expression 0 8 * * *
4. Click on "Schedule the task" button
5. NullPointerException!

stacktrace:
2019-01-22 07:36:21.958  WARN 1 --- [p-nio-80-exec-5] i.f.k.client.internal.VersionUsageUtils  : The client is using resource type 'cronjobs' with unstable version 'v1beta1'
2019-01-22 07:38:38.814 ERROR 1 --- [p-nio-80-exec-4] o.s.c.d.s.c.RestControllerAdvice         : Caught exception while handling a request
java.lang.NullPointerException: null
	at org.springframework.cloud.scheduler.spi.kubernetes.KubernetesScheduler.getExceptionMessageForField(KubernetesScheduler.java:149) ~[spring-cloud-scheduler-kubernetes-1.1.0.BUILD-SNAPSHOT.jar!/:1.1.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.scheduler.spi.kubernetes.KubernetesScheduler.schedule(KubernetesScheduler.java:73) ~[spring-cloud-scheduler-kubernetes-1.1.0.BUILD-SNAPSHOT.jar!/:1.1.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.dataflow.server.service.impl.DefaultSchedulerService.schedule(DefaultSchedulerService.java:147) ~[spring-cloud-dataflow-server-core-2.0.0.BUILD-SNAPSHOT.jar!/:2.0.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.dataflow.server.controller.TaskSchedulerController.save(TaskSchedulerController.java:145) ~[spring-cloud-dataflow-server-core-2.0.0.BUILD-SNAPSHOT.jar!/:2.0.0.BUILD-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_192]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_192]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_192]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_192]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189) ~[spring-web-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) ~[spring-webmvc-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]

**Comment by chrisjs** [comment]
if you are looking to build out of `master`, as of 2.0.x, servers have been consolidated into the data flow project. please see http://docs.spring.io/spring-cloud-dataflow/docs/2.0.0.BUILD-SNAPSHOT/reference/htmlsingle/#getting-started-kubernetes for more details.

for 2.0.x you would want to clone master of https://github.com/spring-cloud/spring-cloud-dataflow and use the deployment files there. 

2.0.x will also require skipper, and you should be applying RBAC rules.

Please give a try following the getting started link above for builds out of 2.0.0 snapshot builds and re-open if your still having issues.

**Comment by rdegracia** [comment]
i am not using skipper as this is for streams only right?

**Comment by chrisjs** [comment]
correct; skipper is for stream deployment: http://docs.spring.io/spring-cloud-dataflow/docs/2.0.0.M1/reference/htmlsingle/#getting-started-kubernetes-deploying-streams

**Comment by rdegracia** [comment]
i will deploy with these settings only for Tasks:
kafka
rbac roles
server
in-mem

(no metrics, no skipper, no redis, no helm)

i will share the results later

**Comment by rdegracia** [comment]
even though I disabled skipper, exception below is coming

2019-01-28 06:01:59.874  WARN 1 --- [p-nio-80-exec-4] o.s.c.d.s.controller.AboutController     : Skipper Server is not accessible

org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://localhost:7577/api/about": Connect to localhost:7577 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused); nested exception is org.apache.http.conn.HttpHostConnectException: Connect to localhost:7577 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)

**Comment by chrisjs** [comment]
* in terms of `even though I disabled skipper, exception below is coming` -- how did you go about disabling it?

* in regards to the exception above starting with: 

```Caused by: java.io.IOException: Cannot run program "docker" (in directory "/tmp/example5506906390460700952/3885003411872550/example-77ba268d-16ff-4fb8-9e6e-cb1f2ab124fc"): error=2, No such file or directory```

this would indicate a configuration error to me as the platform is being configured as local rather than kubernetes. per step 6 (and 5 if using skipper) of http://docs.spring.io/spring-cloud-dataflow/docs/2.0.0.BUILD-SNAPSHOT/reference/htmlsingle/#getting-started-kubernetes-deploy-services-and-data-flow is to apply the `ConfigMap` for the binder you are using, ie: SCDF config for rabbit: `kubectl create -f src/kubernetes/server/server-config-rabbit.yaml`. the key piece here is:

```
          task:
            platform:
              kubernetes:
                accounts:
                  default:
                  ...
```

which would enable the kubernetes platform leading to the kubernetes scheduler being used rather than local.

i would suggest making sure you local `master` clone is current and start from the beginning of the getting started guide, setting this up per the documentation to verify successful startup of the system. once you have verified the setup per the docs, then start removing bits and pieces as you choose.

**Comment by rdegracia** [comment]
disabling skipper in server-deployment.yaml

          # Provide the Skipper service location
        #- name: SPRING_CLOUD_SKIPPER_CLIENT_SERVER_URI
          #value: 'http://${SKIPPER_SERVICE_HOST}/api'

**Comment by rdegracia** [comment]
btw @chrisjs for the configMap, is Mysql and REDIS really needed? As I shared earlier, due to memory resource limitation, I removed this

**Comment by rdegracia** [comment]
I have few more clarifications:
1. When a task is scheduled on specific timings based on the cron expression, once it is met, it will behave the same thing as when click on "Launch" on that task?
2. Existing batch+task application is already running in Kubernetes and I just get the docker image path of this and add it in the SCDF dashboard as Tasks. But I noticed, when I click on "Launch", it is pulling the image and creating its own container. This should refer to the existing batch+task container right?

Error from server (BadRequest): container "testbatch-lx5196jq5n" in pod "testbatch-lx5196jq5n" is waiting to start: trying and failing to pull image

3. In relation to #2, if it is creating its own container (pod), it is consuming addtional resource?

**Comment by chrisjs** [comment]
> btw @chrisjs for the configMap, is Mysql and REDIS really needed? As I shared earlier, due to memory resource limitation, I removed this

mysql isn't required, an embedded h2 in-memory database will be used of none are configured

redis is not needed unless you are using analytics

**Comment by chrisjs** [comment]
> I have few more clarifications:
> 
> 1. When a task is scheduled on specific timings based on the cron expression, once it is met, it will behave the same thing as when click on "Launch" on that task?
> 2. Existing batch+task application is already running in Kubernetes and I just get the docker image path of this and add it in the SCDF dashboard as Tasks. But I noticed, when I click on "Launch", it is pulling the image and creating its own container. This should refer to the existing batch+task container right?
> 
> Error from server (BadRequest): container "testbatch-lx5196jq5n" in pod "testbatch-lx5196jq5n" is waiting to start: trying and failing to pull image
> 
> 1. In relation to #2, if it is creating its own container (pod), it is consuming addtional resource?

re: 1) a task will behave the same way be it you launch it from a cron expression, the UI, or running the container manually -- its just a docker container with your task contained inside.

re: 2) im not following here. you register a task which is associated with the docker image for that task and then you create a schedule with that task, launch it, etc. if your getting `Error from server (BadRequest): container "testbatch-lx5196jq5n" in pod "testbatch-lx5196jq5n" is waiting to start: trying and failing to pull image` - are you able to reach wherever your are trying to pull the image from?

re: 3) when a pod is created and an application starts inside of it, yes, the pod consumes resources -- the pod contains the application.

**Comment by rdegracia** [comment]
re: 1) a task will behave the same way be it you launch it from a cron expression, the UI, or running the container manually -- its just a docker container with your task contained inside.
>> okay got it

re: 2) im not following here. you register a task which is associated with the docker image for that task and then you create a schedule with that task, launch it, etc. if your getting Error from server (BadRequest): container "testbatch-lx5196jq5n" in pod "testbatch-lx5196jq5n" is waiting to start: trying and failing to pull image - are you able to reach wherever your are trying to pull the image from?
>> to get clear picture, below are the steps which I did:
  a. deploy the batch+task application image in kubernetes and this application is in running state since its a spring batch application
  b. get the image name and path of (a) ==> image name is something like "test-994d797bf-v2g2x"
  c. in scdf dashboard, create a new app with the docker image in (b)
  d. create a task of the app created in (c)
  e. add a cron schedule in (d)
  f.  click on Launch (just to verify that this task is executed without issues)
>> I am guessing since this container "testbatch-lx5196jq5n" is created after (f), it's memory is consuming the limited mem resource allocated in the cluster, right?

re: 3) when a pod is created and an application starts inside of it, yes, the pod consumes resources -- the pod contains the application.
>> I am assuming that this prod ("testbatch-lx5196jq5n") is not the actual application ( "test-994d797bf-v2g2x") ?

**Comment by sabbyanandan** [comment]
@rdegracia: For questions like this, please use Gitter or Stackoverflow. We use GitHub for bugs and feature requests.

**Comment by rdegracia** [comment]
@sabbyanandan yes i am aware of this so i have asked same question in Stackoverflow (superuser) but no one responded on that area.

**Comment by rdegracia** [comment]
@sabbyanandan @chrisjs there is no Edit option in SCDF dashboard for existing Applications and/or Tasks?

**Comment by rdegracia** [comment]
@chrisjs i deployed the sample from git as docker image in SCDF dashboard but there is an exception using H2. I found some forums on the versioning but it seems not fixing it.
(https://github.com/spring-cloud/spring-cloud-task/tree/master/spring-cloud-task-samples/batch-job)

scdf server image: springcloud/spring-cloud-dataflow-server:2.0.0.BUILD-SNAPSHOT
h2 version 1.4.195 or 1.4.196 or 1.4.197

Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is org.h2.jdbc.JdbcSQLException: Connection is broken: "java.net.ConnectException: Connection refused (Connection refused): localhost:19092" [90067-195]
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:81) ~[spring-jdbc-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.jdbc.support.JdbcUtils.extractDatabaseMetaData(JdbcUtils.java:319) ~[spring-jdbc-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	... 77 common frames omitted
Caused by: org.h2.jdbc.JdbcSQLException: Connection is broken: "java.net.ConnectException: Connection refused (Connection refused): localhost:19092" [90067-195]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345) ~[h2-1.4.195.jar!/:na]
	at org.h2.message.DbException.get(DbException.java:168) ~[h2-1.4.195.jar!/:na]
	at org.h2.engine.SessionRemote.connectServer(SessionRemote.java:457) ~[h2-1.4.195.jar!/:na]
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:334) ~[h2-1.4.195.jar!/:na]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116) ~[h2-1.4.195.jar!/:na]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:100) ~[h2-1.4.195.jar!/:na]
	at org.h2.Driver.connect(Driver.java:69) ~[h2-1.4.195.jar!/:na]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:136) ~[HikariCP-3.2.0.jar!/:na]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:369) ~[HikariCP-3.2.0.jar!/:na]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:198) ~[HikariCP-3.2.0.jar!/:na]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467) ~[HikariCP-3.2.0.jar!/:na]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:541) ~[HikariCP-3.2.0.jar!/:na]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[HikariCP-3.2.0.jar!/:na]
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) ~[HikariCP-3.2.0.jar!/:na]
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:157) ~[spring-jdbc-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:115) ~[spring-jdbc-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:78) ~[spring-jdbc-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	... 78 common frames omitted
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_111-internal]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_111-internal]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_111-internal]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_111-internal]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_111-internal]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_111-internal]
	at org.h2.util.NetUtils.createSocket(NetUtils.java:123) ~[h2-1.4.195.jar!/:na]
	at org.h2.util.NetUtils.createSocket(NetUtils.java:103) ~[h2-1.4.195.jar!/:na]
	at org.h2.engine.SessionRemote.initTransfer(SessionRemote.java:115) ~[h2-1.4.195.jar!/:na]
	at org.h2.engine.SessionRemote.connectServer(SessionRemote.java:453) ~[h2-1.4.195.jar!/:na]
	... 92 common frames omitted
