### ISSUE TITLE
database row error using multiples values on deploy environment

### ISSUE THREAD

**Issue by eskuai** [spring-cloud/spring-cloud-dataflow-server-kubernetes#379]
I got a database row exception to config multiple properties on deploy
deployer.*.kubernetes.readinessProbePath=/info
deployer.*.kubernetes.livenessProbePath=/health
deployer.*.kubernetes.livenessProbeDelay=120
deployer.*.kubernetes.livenessProbePeriod=90
deployer.*.kubernetes.limits.memory=1024Mi
deployer.*.kubernetes.requests.memory=1024Mi
deployer.*.memory=2048
deployer.*.kubernetes.environmentVariables=JAVA_TOOL_OPTIONS=-Xmx1024m -XX:+UnlockExperimentalVMOptions  -XX:+UseCGroupMemoryLimitForHeap

PreparedStatementCallback; SQL [insert into STREAM_DEPLOYMENTS (STREAM_NAME, DEPLOYMENT_PROPS) values (?, ?)]; (conn=101) Data too long for column 'DEPLOYMENT_PROPS' at row 1 ...

But, it seems pods is running ...

I am using :
scdf 1.7.3 
k8s 1.13
 java 8
mysql

**Comment by sabbyanandan** [comment]
Hi, @eskuai. Thanks for reporting it. The `..` probably refers to the stream-app name in your stream definition. Could you expand on the deployer properties that you listed above? 

It'd be good to also review the stream create/deploy commands for completeness. Of course, please remove or anonymize any sensitive portions of it.

**Comment by eskuai** [comment]
Hi @sabbyanandan 
Thx for your help

Sure, i can't reproduce it simply using 

deployer.*.kubernetes.readinessProbePath=/info
deployer.*.kubernetes.livenessProbePath=/health
deployer.*.kubernetes.livenessProbeDelay=120
deployer.*.kubernetes.livenessProbePeriod=90
deployer.*.kubernetes.limits.memory=1024Mi
deployer.*.kubernetes.requests.memory=1024Mi
deployer.*.memory=2048
deployer.*.kubernetes.environmentVariables=JAVA_TOOL_OPTIONS=-Xmx1024m -XX:+UnlockExperimentalVMOptions  -XX:+UseCGroupMemoryLimitForHeap

Then, if i remove probedealy and probperiod its run ok ...

**Comment by eskuai** [comment]
19-02-18 16:33:49.025  INFO 1 --- [p-nio-80-exec-4] o.s.c.d.s.k.DefaultContainerFactory      : Using Docker image: springcloudstream/time-source-kafka-10:1.3.1.RELEASE
2019-02-18 16:33:49.025  INFO 1 --- [p-nio-80-exec-4] o.s.c.d.s.k.DefaultContainerFactory      : Using Docker entry point style: exec
2019-02-18 16:33:50.857 ERROR 1 --- [p-nio-80-exec-4] o.s.c.d.s.c.RestControllerAdvice         : Caught exception while handling a request
org.springframework.dao.DataIntegrityViolationException: PreparedStatementCallback; SQL [insert into STREAM_DEPLOYMENTS (STREAM_NAME, DEPLOYMENT_PROPS) values (?, ?)]; (conn=121) Data too long for column 'DEPLOYMENT_PROPS' at row 1; nested exception is java.sql.SQLDataException: (conn=121) Data too long for column 'DEPLOYMENT_PROPS' at row 1
        at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.doTranslate(SQLExceptionSubclassTranslator.java:82) ~[spring-jdbc-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73) ~[spring-jdbc-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:82) ~[spring-jdbc-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:655) ~[spring-jdbc-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
        at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:876) ~[spring-jdbc-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
        at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:937) ~[spring-jdbc-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
        at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:942) ~[spring-jdbc-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
        at org.springframework.cloud.dataflow.server.repository.RdbmsStreamDeploymentRepository.save(RdbmsStreamDeploymentRepository.java:60) ~[spring-cloud-dataflow-server-core-1.7.4.RELEASE.jar!/:1.7.4.RELEASE]
        at org.springframework.cloud.dataflow.server.stream.AppDeployerStreamDeployer.deployStream(AppDeployerStreamDeployer.java:150) ~[spring-cloud-dataflow-server-core-1.7.4.RELEASE.jar!/:1.7.4.RELEASE]
        at org.springframework.cloud.dataflow.server.service.impl.AppDeployerStreamService.doDeployStream(AppDeployerStreamService.java:86) ~[spring-cloud-dataflow-server-core-1.7.4.RELEASE.jar!/:1.7.4.RELEASE]
        at org.springframework.cloud.dataflow.server.service.impl.AbstractStreamService.deployStream(AbstractStreamService.java:161) ~[spring-cloud-dataflow-server-core-1.7.4.RELEASE.jar!/:1.7.4.RELEASE]
        at sun.reflect.GeneratedMethodAccessor595.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_192]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_192]
		
		
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.34.jar!/:8.5.34]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_192]
Caused by: java.sql.SQLDataException: (conn=121) Data too long for column 'DEPLOYMENT_PROPS' at row 1
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:225) ~[mariadb-java-client-2.4.0.jar!/:na]
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:165) ~[mariadb-java-client-2.4.0.jar!/:na]
        at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:238) ~[mariadb-java-client-2.4.0.jar!/:na]
        at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:230) ~[mariadb-java-client-2.4.0.jar!/:na]
        at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:157) ~[mariadb-java-client-2.4.0.jar!/:na]
        at org.mariadb.jdbc.ClientSidePreparedStatement.executeUpdate(ClientSidePreparedStatement.java:192) ~[mariadb-java-client-2.4.0.jar!/:na]
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[HikariCP-3.1.0.jar!/:na]
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[HikariCP-3.1.0.jar!/:na]
        at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:883) ~[spring-jdbc-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
        at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:876) ~[spring-jdbc-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:639) ~[spring-jdbc-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
        ... 123 common frames omitted
Caused by: java.sql.SQLException: Data too long for column 'DEPLOYMENT_PROPS' at row 1
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1594) ~[mariadb-java-client-2.4.0.jar!/:na]
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1453) ~[mariadb-java-client-2.4.0.jar!/:na]
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1415) ~[mariadb-java-client-2.4.0.jar!/:na]
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:288) ~[mariadb-java-client-2.4.0.jar!/:na]
        at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:221) ~[mariadb-java-client-2.4.0.jar!/:na]
        ... 130 common frames omitted

**Comment by jvalkeal** [comment]
Looks like we have rather low limit with mysql and I'll bet you're going over(that's the theory).

https://github.com/spring-cloud/spring-cloud-dataflow/blob/7ff427abfd0213112a9f2f90c6e98a3498d1a7f6/spring-cloud-dataflow-server-core/src/main/resources/schemas/mysql/streams.sql#L8

Temporary workaround for you might just be to manually change that column length in mysql db.

**Comment by sabbyanandan** [comment]
Thanks, @jvalkeal.

@eskuai: Please try adjusting it locally to prove the theory; we will review it on our side, and adjust the limit for MySQL on a point release. Do let us know what you find out, though.

**Comment by eskuai** [comment]
Tx @jvalkeal, 

checking my actual mysql table definitions, 

| innodb_index_stats           |
| innodb_table_stats           |
| ndb_binlog_index             |
| plugin                       |
| proc                         |
| procs_priv                   |
| proxies_priv                 |
| servers                      |
| slave_master_info            |
| slave_relay_log_info         |
| slave_worker_info            |
| slow_log                     |
| tables_priv                  |
| time_zone                    |
| time_zone_leap_second        |
| time_zone_name               |
| time_zone_transition         |
| time_zone_transition_type    |
| user                         |
+------------------------------+
49 rows in set (0.00 sec)

MySQL [mysql]> describe STREAM_DEPLOYMENTS ;
+------------------+---------------+------+-----+---------+-------+
| Field            | Type          | Null | Key | Default | Extra |
+------------------+---------------+------+-----+---------+-------+
| STREAM_NAME      | varchar(255)  | NO   | PRI | NULL    |       |
| DEPLOYMENT_PROPS | varchar(1000) | YES  |     | NULL    |       |
+------------------+---------------+------+-----+---------+-------+
2 rows in set (0.00 sec)

It is show that   DEPLOYMENT_PROPS | varchar(1000)  are 1000  
and  i get the same message error:

019-02-18 16:33:49.025  INFO 1 --- [p-nio-80-exec-4] o.s.c.d.s.k.DefaultContainerFactory      : Using Docker entry point style: exec
2019-02-18 16:33:50.857 ERROR 1 --- [p-nio-80-exec-4] o.s.c.d.s.c.RestControllerAdvice         : Caught exception while handling a request
org.springframework.dao.DataIntegrityViolationException: PreparedStatementCallback; SQL [insert into STREAM_DEPLOYMENTS (STREAM_NAME, DEPLOYMENT_PROPS) values (?, ?)]; (conn=121) Data too long for column 'DEPLOYMENT_PROPS' at row 1; nested exception is java.sql.SQLDataException: (conn=121) Data too long for column 'DEPLOYMENT_PROPS' at row 1
        at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.doTranslate(SQLExceptionSubclassTranslator.java:82) ~[spring-jdbc-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73) ~[spring-jdbc-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:82) ~[spring-jdbc-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:655) ~[spring-jdbc-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
        at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:876) ~[spring-jdbc-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
        at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:937) ~[spring-jdbc-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
        at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:942) ~[spring-jdbc-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
        at org.springframework.cloud.dataflow.server.repository.RdbmsStreamDeploymentRepository.save(RdbmsStreamDeploymentRepository.java:60) ~[spring-cloud-dataflow-server-core-1.7.4.RELEASE.jar!/:1.7.4.RELEASE]
        at org.springframework.cloud.dataflow.server.stream.AppDeployerStreamDeployer.deployStream(AppDeployerStreamDeployer.java:150) ~[spring-cloud-dataflow-server-core-1.7.4.RELEASE.jar!/:1.7.4.RELEASE]
        at org.springframework.cloud.dataflow.server.service.impl.AppDeployerStreamService.doDeployStream(AppDeployerStreamService.java:86) ~[spring-cloud-dataflow-server-core-1.7.4.RELEASE.jar!/:1.7.4.RELEASE]
        at org.springframework.cloud.dataflow.server.service.impl.AbstractStreamService.deployStream(AbstractStreamService.java:161) ~[spring-cloud-dataflow-server-core-1.7.4.RELEASE.jar!/:1.7.4.RELEASE]
        at sun.reflect.GeneratedMethodAccessor595.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_192]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_192]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333) ~[spring-aop-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190) ~[spring-aop-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99) ~[spring-

**Comment by jvalkeal** [comment]
We're probably in a point release see if `VARCHAR(max)` works with mysql. I think max length is 65K so set it to whatever you need.

**Comment by eskuai** [comment]
Database changed
MySQL [mysql]> describe DEPLOYMENT_PROPS;
ERROR 1146 (42S02): Table 'mysql.DEPLOYMENT_PROPS' doesn't exist
MySQL [mysql]> describe STREAM_DEPLOYMENTS ;
+------------------+---------------+------+-----+---------+-------+
| Field            | Type          | Null | Key | Default | Extra |
+------------------+---------------+------+-----+---------+-------+
| STREAM_NAME      | varchar(255)  | NO   | PRI | NULL    |       |
| DEPLOYMENT_PROPS | varchar(1000) | YES  |     | NULL    |       |
+------------------+---------------+------+-----+---------+-------+
2 rows in set (0.00 sec)

MySQL [mysql]> alter table STREAM_DEPLOYMENTS MODIFY COLUMN DEPLOYMENT_PROPS VARCHAR(5000);
Query OK, 1 row affected (0.07 sec)
Records: 1  Duplicates: 0  Warnings: 0

MySQL [mysql]>

trying  with 5000 ..  wait a minutes

**Comment by sabbyanandan** [comment]
@eskuai: Thanks for the update! We will address spring-cloud/spring-cloud-dataflow#2922 in v1.7.4.
