### ISSUE TITLE
New version v2.0.0.RELEASE of spring cloud dataflow server kubernetes

### ISSUE THREAD

**Issue by vikasalle** [spring-cloud/spring-cloud-dataflow-server-kubernetes#426]
Waiting for spring-cloud-dataflow-server-kubernetes v2.0.0.RELEASE.

When are we expecting to have docker image spring-cloud-dataflow-server-kubernetes v2.0.0.RELEASE ?

I am getting below error when I try to launch task/trying to access scheduler tab:
2019-04-02 21:25:35.192  INFO 1 --- [           main] o.s.c.d.s.k.KubernetesDataFlowServer     : Started KubernetesDataFlowServer in 43.464 seconds (JVM running for 45.692)
2019-04-02 21:25:35.313  INFO 1 --- [           main] .s.c.d.s.s.LauncherInitializationService : Creating Local Task Launcher named 'default' since no Task Launchers configured.
2019-04-02 21:25:35.398  INFO 1 --- [           main] .s.c.d.s.s.LauncherInitializationService : Added 'Local' platform account 'default' into Task Launcher repository.
2019-04-02 21:25:36.708  INFO 1 --- [p-nio-80-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2019-04-02 21:25:38.533  INFO 1 --- [p-nio-80-exec-4] o.h.h.i.QueryTranslatorFactoryInitiator  : HHH000397: Using ASTQueryTranslatorFactory
2019-04-02 21:25:41.903 ERROR 1 --- [-nio-80-exec-10] o.s.c.d.s.c.RestControllerAdvice         : Caught exception while handling a request

java.lang.IllegalStateException: Could not find a default scheduler.
	at org.springframework.cloud.dataflow.server.service.impl.DefaultSchedulerService.getDefaultLauncher(DefaultSchedulerService.java:172) ~[spring-cloud-dataflow-server-core-2.0.1.RELEASE.jar!/:2.0.1.RELEASE]
	at org.springframework.cloud.dataflow.server.service.impl.DefaultSchedulerService.list(DefaultSchedulerService.java:209) ~[spring-cloud-dataflow-server-core-2.0.1.RELEASE.jar!/:2.0.1.RELEASE]
	at org.springframework.cloud.dataflow.server.controller.TaskSchedulerController.list(TaskSchedulerController.java:84) ~[spring-cloud-dataflow-server-core-2.0.1.RELEASE.jar!/:2.0.1.RELEASE]

**Comment by chrisjs** [comment]
per this repo's readme - "Beginning with Spring Cloud Data Flow v2.0.0, we have consolidated the Local, Cloud Foundry, and Kubernetes servers into a single server. Instead of building, maintaining, and shipping individual server-implementations, we have consolidated them into a single server, and all the supported platform-specific deployer implementation libraries are bundled in it."

you can find the current 2.x release line docs at: http://docs.spring.io/spring-cloud-dataflow/docs/2.0.1.RELEASE/reference/htmlsingle/#getting-started
